- project:
    templates:
      - publish-openstack-sphinx-docs
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - release-notes-jobs
    check:
      jobs:
        - python-manilaclient-functional
        - openstack-tox-cover:
            voting: false
        - rally-dsvm-manila-multibackend:
            voting: false
        - rally-dsvm-manila-multibackend-no-ss:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - python-manilaclient-functional